services:

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=files_mgmt
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data







volumes:
  postgres-volume: